import type { Locale } from '../lib/locales';

export interface DocsCopy {
  title: string; description: string; search: string; searchPlaceholder: string;
  noResults: string; loading: string; searchError: string; retry: string; close: string;
  toc: string; tocPopover: string; lastUpdate: string; chooseLanguage: string;
  next: string; previous: string; edit: string; source: string; version: string;
  translated: string; notFound: string; notFoundDescription: string; returnHome: string;
}

export const docsCopy: Record<Locale, DocsCopy> = {
  'zh-hans': { title: '文档', description: '从第一次连接到理解协议，找到使用 Umbra 所需的一切。', search: '搜索文档', searchPlaceholder: '搜索配置、命令或概念…', noResults: '没有找到相关文档', loading: '正在加载搜索索引…', searchError: '搜索暂时不可用', retry: '重试', close: '关闭', toc: '本页内容', tocPopover: '页面目录', lastUpdate: '最近更新', chooseLanguage: '选择语言', next: '下一篇', previous: '上一篇', edit: '编辑此页', source: '内容来源', version: '适用版本', translated: '已翻译', notFound: '这条路径还没有连接。', notFoundDescription: '页面不存在或已移动。可以回到首页，或在文档中寻找答案。', returnHome: '返回首页' },
  'zh-hant': { title: '文件', description: '從第一次連線到理解協定，找到使用 Umbra 所需的一切。', search: '搜尋文件', searchPlaceholder: '搜尋設定、指令或概念…', noResults: '找不到相關文件', loading: '正在載入搜尋索引…', searchError: '搜尋暫時無法使用', retry: '重試', close: '關閉', toc: '本頁內容', tocPopover: '頁面目錄', lastUpdate: '最近更新', chooseLanguage: '選擇語言', next: '下一篇', previous: '上一篇', edit: '編輯此頁', source: '內容來源', version: '適用版本', translated: '已翻譯', notFound: '這條路徑尚未連接。', notFoundDescription: '頁面不存在或已移動。您可以返回首頁，或從文件尋找答案。', returnHome: '返回首頁' },
  en: { title: 'Documentation', description: 'From your first connection to the protocol underneath. Everything you need to work with Umbra.', search: 'Search documentation', searchPlaceholder: 'Search configuration, commands, concepts…', noResults: 'No matching documents', loading: 'Loading search index…', searchError: 'Search is temporarily unavailable', retry: 'Try again', close: 'Close', toc: 'On this page', tocPopover: 'Table of contents', lastUpdate: 'Last updated', chooseLanguage: 'Choose language', next: 'Next', previous: 'Previous', edit: 'Edit this page', source: 'Sources', version: 'Applies to', translated: 'Translated', notFound: 'This path isn’t connected yet.', notFoundDescription: 'This page does not exist or has moved. Return home, or find your way in the documentation.', returnHome: 'Back to home' },
  fr: { title: 'Documentation', description: 'De votre première connexion aux détails du protocole : tout pour utiliser Umbra.', search: 'Rechercher dans la documentation', searchPlaceholder: 'Configuration, commandes, concepts…', noResults: 'Aucun document correspondant', loading: 'Chargement de l’index…', searchError: 'La recherche est temporairement indisponible', retry: 'Réessayer', close: 'Fermer', toc: 'Sur cette page', tocPopover: 'Table des matières', lastUpdate: 'Dernière mise à jour', chooseLanguage: 'Choisir la langue', next: 'Suivant', previous: 'Précédent', edit: 'Modifier cette page', source: 'Sources', version: 'Version concernée', translated: 'Traduit', notFound: 'Ce chemin n’est pas encore connecté.', notFoundDescription: 'Cette page n’existe pas ou a été déplacée. Revenez à l’accueil ou consultez la documentation.', returnHome: 'Retour à l’accueil' },
  es: { title: 'Documentación', description: 'Desde tu primera conexión hasta los detalles del protocolo. Todo para utilizar Umbra.', search: 'Buscar en la documentación', searchPlaceholder: 'Configuración, comandos, conceptos…', noResults: 'No se encontraron documentos', loading: 'Cargando el índice…', searchError: 'La búsqueda no está disponible temporalmente', retry: 'Reintentar', close: 'Cerrar', toc: 'En esta página', tocPopover: 'Índice', lastUpdate: 'Última actualización', chooseLanguage: 'Elegir idioma', next: 'Siguiente', previous: 'Anterior', edit: 'Editar esta página', source: 'Fuentes', version: 'Versión aplicable', translated: 'Traducido', notFound: 'Esta ruta aún no está conectada.', notFoundDescription: 'La página no existe o se ha movido. Vuelve al inicio o consulta la documentación.', returnHome: 'Volver al inicio' },
  ja: { title: 'ドキュメント', description: '最初の接続からプロトコルの仕組みまで。Umbra を使うためのガイド。', search: 'ドキュメントを検索', searchPlaceholder: '設定、コマンド、概念を検索…', noResults: '該当するドキュメントがありません', loading: '検索インデックスを読み込み中…', searchError: '検索を一時的に利用できません', retry: '再試行', close: '閉じる', toc: 'このページの内容', tocPopover: '目次', lastUpdate: '最終更新', chooseLanguage: '言語を選択', next: '次へ', previous: '前へ', edit: 'このページを編集', source: '参照元', version: '対象バージョン', translated: '翻訳済み', notFound: 'このパスはまだ接続されていません。', notFoundDescription: 'ページが存在しないか、移動されました。ホームに戻るか、ドキュメントをご覧ください。', returnHome: 'ホームに戻る' },
  ca: { title: 'Documentació', description: 'De la primera connexió als detalls del protocol. Tot el que cal per utilitzar Umbra.', search: 'Cerca a la documentació', searchPlaceholder: 'Configuració, ordres, conceptes…', noResults: 'No s’han trobat documents', loading: 'S’està carregant l’índex…', searchError: 'La cerca no està disponible temporalment', retry: 'Torna-ho a provar', close: 'Tanca', toc: 'En aquesta pàgina', tocPopover: 'Taula de continguts', lastUpdate: 'Darrera actualització', chooseLanguage: 'Tria la llengua', next: 'Següent', previous: 'Anterior', edit: 'Edita aquesta pàgina', source: 'Fonts', version: 'Versió aplicable', translated: 'Traduït', notFound: 'Aquest camí encara no està connectat.', notFoundDescription: 'La pàgina no existeix o s’ha mogut. Torna a l’inici o consulta la documentació.', returnHome: 'Torna a l’inici' },
};
